### ISSUE TITLE
setup.sh django not working

### ISSUE THREAD

**Issue by arjun921** [sig-ml/crossval#5]
> Arjuns-MBP:crossval arjuns$ bash setup.sh
>  Virtualenv Found. Using pre existing env. 
>  Installing requirements. 
> setup.sh: /Users/arjuns/Working DIrectory/IIITM-K/crossval/env/bin/pip: "/Users/arjuns/Working: bad interpreter: No such file or directory
>  Setup folder path is:  /Users/arjuns/Working DIrectory/IIITM-K/crossval
>  Webserver Setup started.
>  Removing old Database if any.
> rm: db.sqlite3: No such file or directory
>  Creating new database structures.
> Traceback (most recent call last):
>   File "manage.py", line 8, in <module>
>     from django.core.management import execute_from_command_line
> ImportError: No module named 'django'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "manage.py", line 14, in <module>
>     import django
> ImportError: No module named 'django'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "manage.py", line 17, in <module>
>     "Couldn't import Django. Are you sure it's installed and "
> ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
>  Creating new database.
> Traceback (most recent call last):
>   File "manage.py", line 8, in <module>
>     from django.core.management import execute_from_command_line
> ImportError: No module named 'django'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "manage.py", line 14, in <module>
>     import django
> ImportError: No module named 'django'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "manage.py", line 17, in <module>
>     "Couldn't import Django. Are you sure it's installed and "
> ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
>  Collecting static files.
> Traceback (most recent call last):
>   File "manage.py", line 8, in <module>
>     from django.core.management import execute_from_command_line
> ImportError: No module named 'django'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "manage.py", line 14, in <module>
>     import django
> ImportError: No module named 'django'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "manage.py", line 17, in <module>
>     "Couldn't import Django. Are you sure it's installed and "
> ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
>  Set up a superuser. 
> Traceback (most recent call last):
>   File "manage.py", line 8, in <module>
>     from django.core.management import execute_from_command_line
> ImportError: No module named 'django'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "manage.py", line 14, in <module>
>     import django
> ImportError: No module named 'django'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "manage.py", line 17, in <module>
>     "Couldn't import Django. Are you sure it's installed and "
> ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
>  Setup is done. 

Setup.sh was working fine before..
Not anymore

**Comment by theSage21** [comment]
Since I cannot reproduce this issue, I think it's local to you system.

**Comment by theSage21** [comment]
Also, it's not Django that's missing, it's the naming of your directory that's bad. `Working directory` causes an argument breakup. Fix that space in your directory name.
